todo_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_list_app.urls', namespace='todo_list_app')),
]

todo_list_app/urls.py
from django.urls import path

from todo_list_app.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    change_task_status
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task/<int:pk>/change-task-status/",
        change_task_status,
        name="change-task-status"
    ),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_list_app"

todo_list_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=1023)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name='tasks')

todo_list_app/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo_list_app.models import Tag, Task


class TaskListView(generic.ListView):
    model = Task

    def get_queryset(self):
        return Task.objects.order_by('is_done', '-created_at')


class TaskCreateView(generic.CreateView):
    model = Task
    fields = ["content", "deadline", "tags"]
    success_url = reverse_lazy("todo_list_app:task-list")
    template_name = "todo_list_app/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = ["content", "deadline", "tags"]
    success_url = reverse_lazy("todo_list_app:task-list")
    template_name = "todo_list_app/task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list_app:task-list")
    template_name = "todo_list_app/task_confirm_delete.html"


def change_task_status(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect("/")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list_app:tag-list")
    template_name = "todo_list_app/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list_app:tag-list")
    template_name = "todo_list_app/tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list_app:tag-list")
    template_name = "todo_list_app/tag_confirm_delete.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Taxi Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_list_app:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list_app:tag-list' %}">Tags</a></li>
</ul>

templates/todo_list_app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag</h1>
  <p>Do you want to delete tag: {{ tag }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list_app/tag_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

templates/todo_list_app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags:</h1><a href="{% url 'todo_list_app:tag-create' %}" class="btn btn-primary">New</a>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo_list_app:tag-update' pk=tag.id %}" class="btn btn-primary">Update</a>
          </td>
          <td>
            <a href="{% url 'todo_list_app:tag-delete' pk=tag.id %}" class="btn btn-danger">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No tags</p>
  {% endif %}
{% endblock %}

templates/todo_list_app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag</h1>
  <p>Do you want to delete task?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list_app/task_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

templates/todo_list_app/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tasks:</h1>
  <a href="{% url 'todo_list_app:task-create' %}" class="btn btn-primary">New task</a>
  {% if task_list %}
    <div>
      {% for task in task_list %}
        <div class="task">
          <strong>Status:</strong>
          {% if task.is_done %}
            <span style="color: green">Done</span>
          {% else %}
            <span style="color: red">Not done</span>
          {% endif %}
          <br>
          <strong>Created at:</strong> {{ task.created_at }}
          <br>
          <strong>Deadline:</strong> {{ task.deadline }}
          <br>
          <strong>Content:</strong> {{ task.content }}
          <br>
          <strong>Tags:</strong>
          {% if task.tags %}
            {% for tag in task.tags.all %}
              <u>#{{ tag.name }}</u>,
            {% endfor %}
          {% else %}
            <p>no tags</p>
          {% endif %}
          <br>
          <p>
            <a href="{% url 'todo_list_app:task-update' pk=task.id %}" class="btn btn-primary">Update</a>
            <a href="{% url 'todo_list_app:task-delete' pk=task.id %}" class="btn btn-danger">Delete</a>
            {% if task.is_done %}
              <a href="{% url 'todo_list_app:change-task-status' pk=task.id %}" class="btn btn-secondary">Undo</a>
            {% else %}
              <a href="{% url 'todo_list_app:change-task-status' pk=task.id %}" class="btn btn-primary">Done</a>
            {% endif %}
          </p>
        </div>
      {% endfor %}
    </div>

    <hr/>

  {% else %}
    <p>No tasks</p>
  {% endif %}
{% endblock %}